name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
      - run: flutter doctor -v

      - name: Install requirements for sqflite_common_ffi package
        run: sudo apt-get -y install libsqlite3-0 libsqlite3-dev

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - name: Verify formatting
        run: |
          dart format .
          cat lib/src/view/account/edit_profile_screen.dart
        # run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run riverpod lint
        run: dart run custom_lint

      - name: Run unit tests
        run: flutter test

